<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>606461d0-7d8b-46a0-b36f-8602abb335c8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Basket\Basket.csproj" />
    <ProjectReference Include="..\Catalog\Catalog.csproj" />
  </ItemGroup>

</Project>
